/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DataBase.JDBCConnector;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Lop;

/**
 *
 * @author Admin
 */
public class LopJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LopJFrame
     */
    private String data;
    public LopJFrame(String data) {
        initComponents();
        this.data = data;
        showData();
    }

    LopJFrame() {
        
    }
    public ArrayList<Lop> dsLop(){
        ArrayList<Lop> dslop = new ArrayList<Lop>();
        Connection con = JDBCConnector.getConnection();
        String sql = "SELECT * FROM lop WHERE khoaid = '"+data+"'";
        Statement st;
        ResultSet rs;
        try {
            st = con.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                Lop l = new Lop(rs.getInt("lopid"),rs.getString("lopname"),rs.getInt("khoaid"));
                dslop.add(l);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return dslop;
    }
    public void showData(){
        DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();
        ArrayList<Lop> list = dsLop();
        for (Lop lop : list) {
            Vector v = new Vector();
            v.add(lop.getMalop());
            v.add(lop.getTenlop());
            model1.addRow(v);
        }
    }
    public void thucthi(String sql, String message){
        Connection con = JDBCConnector.getConnection();
        Statement st;
        try {
           
            st = con.createStatement();
            if(st.executeUpdate(sql) == 1){
                 DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                JOptionPane.showMessageDialog(rootPane, message + "Thành Công");
            }else{
                JOptionPane.showMessageDialog(rootPane, message + "Thất Bại");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        xembtn = new javax.swing.JButton();
        thembtn = new javax.swing.JButton();
        suabtn = new javax.swing.JButton();
        xoabtn = new javax.swing.JButton();
        returnbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lopidtxt = new javax.swing.JTextField();
        lopnametxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Danh Sách Lớp");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Lớp", "Tên Lớp"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        xembtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        xembtn.setText("Xem Danh Sách Học Sinh");
        xembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xembtnActionPerformed(evt);
            }
        });

        thembtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        thembtn.setText("Thêm Lớp");
        thembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thembtnActionPerformed(evt);
            }
        });

        suabtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        suabtn.setText("Sửa Lớp");
        suabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suabtnActionPerformed(evt);
            }
        });

        xoabtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        xoabtn.setText("Xóa Lớp");
        xoabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoabtnActionPerformed(evt);
            }
        });

        returnbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        returnbtn.setText("Quay Lại");
        returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Thông Tin Chi Tiết");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Mã Lớp");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Tên Lớp");

        lopidtxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lopnametxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(xembtn)
                                                .addGap(51, 51, 51)
                                                .addComponent(thembtn)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                                .addComponent(suabtn))
                                            .addComponent(jLabel2)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lopnametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                            .addComponent(lopidtxt))))
                                .addGap(56, 56, 56)
                                .addComponent(xoabtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(returnbtn)
                                .addGap(25, 25, 25)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lopidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lopnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xembtn)
                    .addComponent(thembtn)
                    .addComponent(suabtn)
                    .addComponent(xoabtn)
                    .addComponent(returnbtn))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thembtnActionPerformed
        String sql = "INSERT INTO lop(lopid,lopname,khoaid) VALUES('"+lopidtxt.getText()+"','"+lopnametxt.getText()+"','"+data+"')";
        thucthi(sql, "Thêm");
        showData();
    }//GEN-LAST:event_thembtnActionPerformed

    private void returnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbtnActionPerformed
        this.dispose();
        KhoaJFrame frame = new KhoaJFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_returnbtnActionPerformed

    private void xembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xembtnActionPerformed
       ArrayList<Lop> list = dsLop();
       int i = jTable2.getSelectedRow();
       Lop l = list.get(i);
       lopidtxt.setText(l.getMalop() + " ");
       lopnametxt.setText(l.getTenlop());
       HocSinhJframe1 frame = new HocSinhJframe1(lopidtxt.getText());
       this.dispose();
       frame.setVisible(true);
        
    }//GEN-LAST:event_xembtnActionPerformed

    private void suabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suabtnActionPerformed
        String sql = "UPDATE lop SET lopname = '"+lopnametxt.getText()+"' WHERE lopid = '"+lopidtxt.getText()+"'";
        thucthi(sql, "Sửa");
        showData();
    }//GEN-LAST:event_suabtnActionPerformed

    private void xoabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoabtnActionPerformed
        String sql = "DELETE FROM lop WHERE lopid = '"+lopidtxt.getText()+"'";
        thucthi(sql, "Xóa");
        showData();
    }//GEN-LAST:event_xoabtnActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
       DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
       int i  = jTable2.getSelectedRow();
       lopidtxt.setText(model.getValueAt(i, 0).toString());
       lopnametxt.setText(model.getValueAt(i, 1).toString());
       
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LopJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LopJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LopJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LopJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LopJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lopidtxt;
    private javax.swing.JTextField lopnametxt;
    private javax.swing.JButton returnbtn;
    private javax.swing.JButton suabtn;
    private javax.swing.JButton thembtn;
    private javax.swing.JButton xembtn;
    private javax.swing.JButton xoabtn;
    // End of variables declaration//GEN-END:variables
}
