/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Admin
 */
public class TrangChuFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuFrame
     */
    public TrangChuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seeAllStudent = new javax.swing.JButton();
        seeAllClass = new javax.swing.JButton();
        seeAllKhoa = new javax.swing.JButton();
        seeAllAcount = new javax.swing.JButton();
        Seenomarl = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seeAllStudent.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        seeAllStudent.setText("Quản Lý Học Sinh");
        seeAllStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAllStudentActionPerformed(evt);
            }
        });

        seeAllClass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        seeAllClass.setText("Quản Lý Lớp Học");
        seeAllClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAllClassActionPerformed(evt);
            }
        });

        seeAllKhoa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        seeAllKhoa.setText("Quản Lý Khoa");
        seeAllKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAllKhoaActionPerformed(evt);
            }
        });

        seeAllAcount.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        seeAllAcount.setText("Quản Lý Tài Khoản");
        seeAllAcount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeAllAcountActionPerformed(evt);
            }
        });

        Seenomarl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Seenomarl.setText("Quản Lý Theo Khoa");
        Seenomarl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeenomarlActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Quản Lý Môn Học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seeAllClass)
                    .addComponent(seeAllStudent)
                    .addComponent(Seenomarl))
                .addGap(139, 139, 139)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(seeAllKhoa)
                    .addComponent(seeAllAcount))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seeAllStudent)
                    .addComponent(seeAllKhoa))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(seeAllClass))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(seeAllAcount)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seenomarl)
                    .addComponent(jButton1))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seeAllStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAllStudentActionPerformed
        ALLHocSinhJFrame frame = new ALLHocSinhJFrame();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seeAllStudentActionPerformed

    private void seeAllKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAllKhoaActionPerformed
        ALLKhoaJFrame frame1 = new ALLKhoaJFrame();
        frame1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seeAllKhoaActionPerformed

    private void seeAllClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAllClassActionPerformed
        ALLLopJframe frame2 = new ALLLopJframe();
        frame2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_seeAllClassActionPerformed

    private void seeAllAcountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeAllAcountActionPerformed
       HocSinhAcountJFrame frame4 = new HocSinhAcountJFrame();
       frame4.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_seeAllAcountActionPerformed

    private void SeenomarlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeenomarlActionPerformed
         KhoaJFrame frame3 = new KhoaJFrame();
        frame3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SeenomarlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Seenomarl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton seeAllAcount;
    private javax.swing.JButton seeAllClass;
    private javax.swing.JButton seeAllKhoa;
    private javax.swing.JButton seeAllStudent;
    // End of variables declaration//GEN-END:variables
}
